name: mvp-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Deploy Application to Code Engine
      uses: IBM/code-engine-github-action@v1
      with:
        api-key: ${{ secrets.IBM_IAM_API_KEY }}
        resource-group: 'kanadon'
        region: 'us-south'
        project: 'kanadon-toolchaintest'
        component: 'app'
        name: 'github-action-test'
        build-source: './'
        cpu: 1
        memory: 4G
